# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 270422434c77e205facec1fa8ff4f4cbc6dcd4db70a0a08ccc135ab85af0ef6d519c7e4f252929ff54d6749f46e410d30156f109594ed81695830a5791f806fb

test:
  secret_key_base: 182d94ada366c5b6e78633d45a049a28b6aec74e095a8cbc47505df33c90235d335873fa0f7cefab092720864fee0ea25cb2d22a3d9743ece27c5e75c7ae8576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
